name: mlperf-retinanet
channels:
  - defaults
dependencies:
  - python~=3.11.0
  - pip:
      - torch==2.1.0
      - torchvision==0.16.0
      - numpy==1.26.2
      - opencv-python-headless==4.8.1.78
      - pycocotools==2.0.7
